# Generated by Django 2.2.5 on 2019-10-13 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20190916_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='WUser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
