# Generated by Django 2.2.5 on 2019-10-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_auto_20191013_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_owner+', to=settings.AUTH_USER_MODEL)),
                ('tosend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
