# Generated by Django 2.2.5 on 2019-10-13 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='remark',
            field=models.CharField(default=datetime.datetime(2019, 10, 13, 16, 12, 35, 649353, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
