# Generated by Django 2.2.5 on 2019-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20191014_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
